# /Users/brandonminner/.config/tmuxinator/ruby-project.yml

name: ruby-project
root: ~/repos/<%= @args[0] %>

windows:
  - console:
      layout: even-horizontal
      panes:
        - hub dev up
        - rails c
  - <%= @args[0] %>:
      layout: even-horizontal
      panes:
        - nvim .
